from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "owner-signal-lab-structural-extremes-review.js"
text = PATH.read_text(encoding="utf-8")
old = '''function nearestAlgorithmExtreme(point) {\n  const snapshot = current?.snapshot;\n  if (!snapshot || !chart.layout) return null;\n  const source = elements.showHistory.checked ? snapshot.history : snapshot.active;\n  let best = null;\n  for (const extreme of source) {\n    const origin = screenPointFor(extreme.extremeAt, extreme.price);\n    if (!origin) continue;\n    if (point.candle.time < extreme.extremeAt || point.x < origin.x - 10) continue;\n    const verticalDistance = Math.abs(point.y - origin.y);\n    if (verticalDistance > 30) continue;\n    const score = verticalDistance + Math.min(10, Math.max(0, origin.x - point.x));\n    if (!best || score < best.score) best = { extreme, score };\n  }\n  return best?.extreme ?? null;\n}\n'''
new = '''function nearestVisibleStructuralLevel(point) {\n  if (!chart.layout) return null;\n  const levels = Array.isArray(chart.structuralLevelMap) ? chart.structuralLevelMap : [];\n  let best = null;\n  for (const level of levels) {\n    if (!level || !["HIGH", "LOW"].includes(level.side)) continue;\n    const startAt = finite(level.displayAt ?? level.extremeAt);\n    const price = finite(level.price);\n    if (startAt === null || !(price > 0)) continue;\n    const origin = screenPointFor(startAt, price);\n    if (!origin) continue;\n    if (point.candle.time < startAt || point.x < origin.x - 10) continue;\n    const verticalDistance = Math.abs(point.y - origin.y);\n    if (verticalDistance > 30) continue;\n    const score = verticalDistance + Math.min(10, Math.max(0, origin.x - point.x));\n    if (!best || score < best.score) {\n      best = {\n        score,\n        target: {\n          id: level.id,\n          side: level.side,\n          price,\n          extremeAt: finite(level.nativeExtremeAt ?? level.extremeAt) ?? startAt,\n          displayAt: startAt,\n          sourceTimeframe: level.sourceTimeframe,\n          sources: level.sources,\n          hierarchical: true,\n        },\n      };\n    }\n  }\n  return best?.target ?? null;\n}\n\nfunction nearestAlgorithmExtreme(point) {\n  // V4.6 review fix: the hierarchy owns the visible algorithmic rays. Review\n  // tools must hit-test that exact working map first; otherwise a trader can\n  // click a visible L/H line and still get \"not in extreme\" because the raw\n  // current-TF snapshot is a different dataset.\n  const visibleLevel = nearestVisibleStructuralLevel(point);\n  if (visibleLevel) return visibleLevel;\n\n  const snapshot = current?.snapshot;\n  if (!snapshot || !chart.layout) return null;\n  const source = elements.showHistory.checked ? snapshot.history : snapshot.active;\n  let best = null;\n  for (const extreme of source) {\n    const origin = screenPointFor(extreme.extremeAt, extreme.price);\n    if (!origin) continue;\n    if (point.candle.time < extreme.extremeAt || point.x < origin.x - 10) continue;\n    const verticalDistance = Math.abs(point.y - origin.y);\n    if (verticalDistance > 30) continue;\n    const score = verticalDistance + Math.min(10, Math.max(0, origin.x - point.x));\n    if (!best || score < best.score) best = { extreme, score };\n  }\n  return best?.extreme ?? null;\n}\n'''
if text.count(old) != 1:
    raise SystemExit(f"expected one nearestAlgorithmExtreme block, found {text.count(old)}")
PATH.write_text(text.replace(old, new, 1), encoding="utf-8")

# Static regression is intentional: this UI module is browser-bound and cannot be
# imported safely in node without a DOM. Verify that review hit-testing now owns
# the visible hierarchy before raw snapshot fallback.
test = ROOT / "test/signal-lab-v7-review-hit-target.test.js"
test.write_text('''import test from "node:test";\nimport assert from "node:assert/strict";\nimport fs from "node:fs";\n\nconst source = fs.readFileSync(new URL("../owner-signal-lab-structural-extremes-review.js", import.meta.url), "utf8");\n\ntest("review tools hit-test visible hierarchical levels before raw snapshot", () => {\n  assert.match(source, /function nearestVisibleStructuralLevel\\(point\\)/);\n  assert.match(source, /chart\\.structuralLevelMap/);\n  const visible = source.indexOf("const visibleLevel = nearestVisibleStructuralLevel(point)");\n  const snapshot = source.indexOf("const snapshot = current?.snapshot", visible);\n  assert.ok(visible >= 0);\n  assert.ok(snapshot > visible);\n});\n''', encoding="utf-8")
